// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	measurement "github.com/clambin/sciensano/measurement"
	mock "github.com/stretchr/testify/mock"
)

// Getter is an autogenerated mock type for the Getter type
type Getter struct {
	mock.Mock
}

// GetBatches provides a mock function with given fields: ctx
func (_m *Getter) GetBatches(ctx context.Context) ([]measurement.Measurement, error) {
	ret := _m.Called(ctx)

	var r0 []measurement.Measurement
	if rf, ok := ret.Get(0).(func(context.Context) []measurement.Measurement); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]measurement.Measurement)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
