with-expecter: true
filename: "{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/clambin/sciensano/v2/internal/reports/datasource:
    interfaces:
      Fetcher:
  github.com/clambin/sciensano/v2/internal/reports/reporter:
    interfaces:
      Publisher:
      PopulationFetcher:
  github.com/clambin/sciensano/v2/internal/server:
    interfaces:
      ReportsStore:
