{
 "title": "Sciensano - Hospitalisations",
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Hospitalisations",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "target": "hospitalisations", "type": "table" }
   ]
  },
  {
   "title": "Hospitalisations By Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "hospitalisations-region", "type": "table" }
   ]
  },
  {
   "title": "Hospitalisations By Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "target": "hospitalisations-region", "type": "table" }
   ]
  },
  {
   "title": "Hospitalisations By Province",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "hospitalisations-province", "type": "table" }
   ]
  },
  {
   "title": "Hospitalisations By Province",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    { "target": "hospitalisations-province", "type": "table" }
   ]
  }
 ]
}