{
 "title": "Sciensano - internal",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "API calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(sciensano_api_requests_total[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "API error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(sciensano_api_request_errors_total[5m]) / rate(sciensano_api_requests_total[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "API latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (rate(sciensano_api_latency_sum[5m]) / rate(sciensano_api_latency_count[5m]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (endpoint) (sciensano_cache_hit_total / (sciensano_cache_miss_total+sciensano_cache_hit_total))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  }
 ]
}