{
 "title": "Sciensano - Mortality",
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "New Deaths",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "target": "mortality", "type": "table" }
   ]
  },
  {
   "title": "Total deaths by Age Group",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "mortality-age", "type": "table" }
   ]
  },
  {
   "title": "New deaths by Age Group",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "target": "mortality-age", "type": "table" }
   ]
  },
  {
   "title": "Total deaths by Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "mortality-region", "type": "table" }
   ]
  },
  {
   "title": "New deaths by Region",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    { "target": "mortality-region", "type": "table" }
   ]
  }
 ]
}