{
 "title": "Sciensano",
 "time": { "from": "now-90d", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Tests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "tests", "type": "table" }
   ]
  },
  {
   "title": "Vaccinations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "vaccinations", "type": "table" }
   ]
  },
  {
   "title": "Time till complete vaccination",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "vaccination-lag", "type": "table" }
   ]
  },
  {
   "title": "Vaccines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "vaccinations", "type": "table" },
    { "target": "vaccines", "type": "table" }
   ]
  },
  { "title": "Vaccinations by Age Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Vaccinations by age - Partial",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "vacc-age-partial", "type": "table" }
   ]
  },
  {
   "title": "Vaccinations by age - Full",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "vacc-age-full", "type": "table" }
   ]
  },
  {
   "title": "Vaccination rate by age - Partial",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "target": "vacc-age-rate-partial", "type": "table" }
   ]
  },
  {
   "title": "Vaccination rate by age - Full",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "target": "vacc-age-rate-full", "type": "table" }
   ]
  },
  {
   "title": "Vaccinations by age - Partial",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-age-rate-partial", "type": "table" }
   ]
  },
  {
   "title": "Vaccinations by age - Full",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-age-rate-full", "type": "table" }
   ]
  },
  { "title": "Vaccinations by region", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Vaccinations by region - Partial",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "vacc-region-partial", "type": "table" }
   ]
  },
  {
   "title": "Vaccinations by region - Full",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "vacc-region-full", "type": "table" }
   ]
  },
  {
   "title": "Vaccination rate by region - Partial",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "target": "vacc-region-rate-partial", "type": "table" }
   ]
  },
  {
   "title": "Vaccination rate by region - Full",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "target": "vacc-region-rate-full", "type": "table" }
   ]
  },
  {
   "title": "Vaccinations by region - Partial",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-region-rate-partial", "type": "table" }
   ]
  },
  {
   "title": "Vaccinations by region - Full",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-region-rate-full", "type": "table" }
   ]
  }
 ]
}