{
 "title": "Sciensano - Vaccinations",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Vaccinations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "vaccinations", "type": "table" }
   ]
  },
  {
   "title": "Vaccinations by Manufacturer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "vacc-manufacturer", "type": "table" }
   ]
  },
  {
   "title": "Time to get 2nd vaccination",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "vaccination-lag", "type": "table" }
   ]
  },
  {
   "title": "Time to administer received vaccines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "target": "vaccines-time", "type": "table" }
   ]
  },
  {
   "title": "Vaccines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "vaccines", "type": "table" },
    { "target": "vaccines-stats", "type": "table" }
   ]
  },
  {
   "title": "Vaccines by Manufacturer",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vaccines-manufacturer", "type": "table" }
   ]
  },
  {
   "title": "Vaccinations by Age Group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Partial",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "target": "vacc-age-rate-partial", "type": "table" }
   ]
  },
  {
   "title": "Full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "target": "vacc-age-rate-full", "type": "table" }
   ]
  },
  {
   "title": "Partial",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-age-rate-partial", "type": "table" }
   ]
  },
  {
   "title": "Full",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-age-rate-full", "type": "table" }
   ]
  },
  {
   "title": "Booster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "target": "vacc-age-rate-booster", "type": "table" }
   ]
  },
  {
   "title": "Booster 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "target": "vacc-age-rate-booster2", "type": "table" }
   ]
  },
  {
   "title": "Booster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-age-rate-booster", "type": "table" }
   ]
  },
  {
   "title": "Booster 2",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-age-rate-booster2", "type": "table" }
   ]
  },
  {
   "title": "Vaccinations by region",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Partial",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "target": "vacc-region-rate-partial", "type": "table" }
   ]
  },
  {
   "title": "Full",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "target": "vacc-region-rate-full", "type": "table" }
   ]
  },
  {
   "title": "Partial",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-region-rate-partial", "type": "table" }
   ]
  },
  {
   "title": "Full",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-region-rate-full", "type": "table" }
   ]
  },
  {
   "title": "Booster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "target": "vacc-region-rate-booster", "type": "table" }
   ]
  },
  {
   "title": "Booster 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "target": "vacc-region-rate-booster2", "type": "table" }
   ]
  },
  {
   "title": "Booster",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-region-rate-booster", "type": "table" }
   ]
  },
  {
   "title": "Booster 2",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "vacc-region-rate-booster2", "type": "table" }
   ]
  }
 ]
}