// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package sciensano

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson69364dd1DecodeGithubComClambinSciensanoApiclient(in *jlexer.Lexer, out *APICasesResponseEntry) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "DATE":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.TimeStamp).UnmarshalJSON(data))
			}
		case "PROVINCE":
			out.Province = string(in.String())
		case "REGION":
			out.Region = string(in.String())
		case "AGEGROUP":
			out.AgeGroup = string(in.String())
		case "CASES":
			out.Cases = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson69364dd1EncodeGithubComClambinSciensanoApiclient(out *jwriter.Writer, in APICasesResponseEntry) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"DATE\":"
		out.RawString(prefix[1:])
		out.Raw((in.TimeStamp).MarshalJSON())
	}
	{
		const prefix string = ",\"PROVINCE\":"
		out.RawString(prefix)
		out.String(string(in.Province))
	}
	{
		const prefix string = ",\"REGION\":"
		out.RawString(prefix)
		out.String(string(in.Region))
	}
	{
		const prefix string = ",\"AGEGROUP\":"
		out.RawString(prefix)
		out.String(string(in.AgeGroup))
	}
	{
		const prefix string = ",\"CASES\":"
		out.RawString(prefix)
		out.Int(int(in.Cases))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v APICasesResponseEntry) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson69364dd1EncodeGithubComClambinSciensanoApiclient(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v APICasesResponseEntry) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson69364dd1EncodeGithubComClambinSciensanoApiclient(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *APICasesResponseEntry) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson69364dd1DecodeGithubComClambinSciensanoApiclient(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *APICasesResponseEntry) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson69364dd1DecodeGithubComClambinSciensanoApiclient(l, v)
}
func easyjson69364dd1DecodeGithubComClambinSciensanoApiclient1(in *jlexer.Lexer, out *APICasesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(APICasesResponse, 0, 8)
			} else {
				*out = APICasesResponse{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 *APICasesResponseEntry
			if in.IsNull() {
				in.Skip()
				v1 = nil
			} else {
				if v1 == nil {
					v1 = new(APICasesResponseEntry)
				}
				(*v1).UnmarshalEasyJSON(in)
			}
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson69364dd1EncodeGithubComClambinSciensanoApiclient1(out *jwriter.Writer, in APICasesResponse) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			if v3 == nil {
				out.RawString("null")
			} else {
				(*v3).MarshalEasyJSON(out)
			}
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v APICasesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson69364dd1EncodeGithubComClambinSciensanoApiclient1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v APICasesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson69364dd1EncodeGithubComClambinSciensanoApiclient1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *APICasesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson69364dd1DecodeGithubComClambinSciensanoApiclient1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *APICasesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson69364dd1DecodeGithubComClambinSciensanoApiclient1(l, v)
}
