// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	vaccines "github.com/clambin/sciensano/vaccines"
	mock "github.com/stretchr/testify/mock"
)

// APIClient is an autogenerated mock type for the APIClient type
type APIClient struct {
	mock.Mock
}

// GetBatches provides a mock function with given fields: ctx
func (_m *APIClient) GetBatches(ctx context.Context) ([]*vaccines.Batch, error) {
	ret := _m.Called(ctx)

	var r0 []*vaccines.Batch
	if rf, ok := ret.Get(0).(func(context.Context) []*vaccines.Batch); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*vaccines.Batch)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
