// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Demographics is an autogenerated mock type for the Demographics type
type Demographics struct {
	mock.Mock
}

// AutoRefresh provides a mock function with given fields: ctx, interval
func (_m *Demographics) AutoRefresh(ctx context.Context, interval time.Duration) {
	_m.Called(ctx, interval)
}

// GetAgeGroupFigures provides a mock function with given fields:
func (_m *Demographics) GetAgeGroupFigures() map[string]int {
	ret := _m.Called()

	var r0 map[string]int
	if rf, ok := ret.Get(0).(func() map[string]int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	return r0
}

// GetRegionFigures provides a mock function with given fields:
func (_m *Demographics) GetRegionFigures() map[string]int {
	ret := _m.Called()

	var r0 map[string]int
	if rf, ok := ret.Get(0).(func() map[string]int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	return r0
}

// Stats provides a mock function with given fields:
func (_m *Demographics) Stats() map[string]int {
	ret := _m.Called()

	var r0 map[string]int
	if rf, ok := ret.Get(0).(func() map[string]int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	return r0
}
