package reports

import (
	"github.com/clambin/go-common/cache"
	"github.com/clambin/go-common/tabulator"
	"time"
)

var _ Cache = &LocalCache{}

// LocalCache caches the different reports generated by the server
type LocalCache struct {
	*cache.Cache[string, *tabulator.Tabulator]
}

func NewLocalCache(expiration time.Duration) *LocalCache {
	return &LocalCache{Cache: cache.New[string, *tabulator.Tabulator](expiration, 2*expiration)}
}

func (cache *LocalCache) Get(key string) (*tabulator.Tabulator, error) {
	if entry, ok := cache.Cache.Get(key); ok {
		return entry, nil
	}
	return nil, ErrMissedCache
}

func (cache *LocalCache) Set(key string, table *tabulator.Tabulator) error {
	cache.Cache.Add(key, table)
	return nil
}
