// Code generated by mockery v2.32.2. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	tabulator "github.com/clambin/go-common/tabulator"
)

// ReportsStore is an autogenerated mock type for the ReportsStore type
type ReportsStore struct {
	mock.Mock
}

type ReportsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ReportsStore) EXPECT() *ReportsStore_Expecter {
	return &ReportsStore_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: _a0
func (_m *ReportsStore) Get(_a0 string) (*tabulator.Tabulator, error) {
	ret := _m.Called(_a0)

	var r0 *tabulator.Tabulator
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*tabulator.Tabulator, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *tabulator.Tabulator); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tabulator.Tabulator)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportsStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ReportsStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 string
func (_e *ReportsStore_Expecter) Get(_a0 interface{}) *ReportsStore_Get_Call {
	return &ReportsStore_Get_Call{Call: _e.mock.On("Get", _a0)}
}

func (_c *ReportsStore_Get_Call) Run(run func(_a0 string)) *ReportsStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ReportsStore_Get_Call) Return(_a0 *tabulator.Tabulator, _a1 error) *ReportsStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReportsStore_Get_Call) RunAndReturn(run func(string) (*tabulator.Tabulator, error)) *ReportsStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function with given fields: _a0, _a1
func (_m *ReportsStore) Put(_a0 string, _a1 *tabulator.Tabulator) {
	_m.Called(_a0, _a1)
}

// ReportsStore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type ReportsStore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - _a0 string
//   - _a1 *tabulator.Tabulator
func (_e *ReportsStore_Expecter) Put(_a0 interface{}, _a1 interface{}) *ReportsStore_Put_Call {
	return &ReportsStore_Put_Call{Call: _e.mock.On("Put", _a0, _a1)}
}

func (_c *ReportsStore_Put_Call) Run(run func(_a0 string, _a1 *tabulator.Tabulator)) *ReportsStore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*tabulator.Tabulator))
	})
	return _c
}

func (_c *ReportsStore_Put_Call) Return() *ReportsStore_Put_Call {
	_c.Call.Return()
	return _c
}

func (_c *ReportsStore_Put_Call) RunAndReturn(run func(string, *tabulator.Tabulator)) *ReportsStore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// NewReportsStore creates a new instance of ReportsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReportsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReportsStore {
	mock := &ReportsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
