// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package apiclient

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson99efb7acDecodeGithubComClambinSciensanoApiclient(in *jlexer.Lexer, out *APITestResultsResponseEntry) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "DATE":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.TimeStamp).UnmarshalJSON(data))
			}
		case "PROVINCE":
			out.Province = string(in.String())
		case "REGION":
			out.Region = string(in.String())
		case "TESTS_ALL":
			out.Total = int(in.Int())
		case "TESTS_ALL_POS":
			out.Positive = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson99efb7acEncodeGithubComClambinSciensanoApiclient(out *jwriter.Writer, in APITestResultsResponseEntry) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"DATE\":"
		out.RawString(prefix[1:])
		out.Raw((in.TimeStamp).MarshalJSON())
	}
	{
		const prefix string = ",\"PROVINCE\":"
		out.RawString(prefix)
		out.String(string(in.Province))
	}
	{
		const prefix string = ",\"REGION\":"
		out.RawString(prefix)
		out.String(string(in.Region))
	}
	{
		const prefix string = ",\"TESTS_ALL\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	{
		const prefix string = ",\"TESTS_ALL_POS\":"
		out.RawString(prefix)
		out.Int(int(in.Positive))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v APITestResultsResponseEntry) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson99efb7acEncodeGithubComClambinSciensanoApiclient(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v APITestResultsResponseEntry) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson99efb7acEncodeGithubComClambinSciensanoApiclient(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *APITestResultsResponseEntry) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson99efb7acDecodeGithubComClambinSciensanoApiclient(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *APITestResultsResponseEntry) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson99efb7acDecodeGithubComClambinSciensanoApiclient(l, v)
}
func easyjson99efb7acDecodeGithubComClambinSciensanoApiclient1(in *jlexer.Lexer, out *APITestResultsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(APITestResultsResponse, 0, 0)
			} else {
				*out = APITestResultsResponse{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 APITestResultsResponseEntry
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson99efb7acEncodeGithubComClambinSciensanoApiclient1(out *jwriter.Writer, in APITestResultsResponse) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v APITestResultsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson99efb7acEncodeGithubComClambinSciensanoApiclient1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v APITestResultsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson99efb7acEncodeGithubComClambinSciensanoApiclient1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *APITestResultsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson99efb7acDecodeGithubComClambinSciensanoApiclient1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *APITestResultsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson99efb7acDecodeGithubComClambinSciensanoApiclient1(l, v)
}
