// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package apiclient

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson320b91e2DecodeGithubComClambinSciensanoApiclient(in *jlexer.Lexer, out *APIVaccinationsResponseEntry) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "DATE":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.TimeStamp).UnmarshalJSON(data))
			}
		case "REGION":
			out.Region = string(in.String())
		case "AGEGROUP":
			out.AgeGroup = string(in.String())
		case "SEX":
			out.Gender = string(in.String())
		case "DOSE":
			out.Dose = string(in.String())
		case "COUNT":
			out.Count = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson320b91e2EncodeGithubComClambinSciensanoApiclient(out *jwriter.Writer, in APIVaccinationsResponseEntry) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"DATE\":"
		out.RawString(prefix[1:])
		out.Raw((in.TimeStamp).MarshalJSON())
	}
	{
		const prefix string = ",\"REGION\":"
		out.RawString(prefix)
		out.String(string(in.Region))
	}
	{
		const prefix string = ",\"AGEGROUP\":"
		out.RawString(prefix)
		out.String(string(in.AgeGroup))
	}
	{
		const prefix string = ",\"SEX\":"
		out.RawString(prefix)
		out.String(string(in.Gender))
	}
	{
		const prefix string = ",\"DOSE\":"
		out.RawString(prefix)
		out.String(string(in.Dose))
	}
	{
		const prefix string = ",\"COUNT\":"
		out.RawString(prefix)
		out.Int(int(in.Count))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v APIVaccinationsResponseEntry) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson320b91e2EncodeGithubComClambinSciensanoApiclient(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v APIVaccinationsResponseEntry) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson320b91e2EncodeGithubComClambinSciensanoApiclient(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *APIVaccinationsResponseEntry) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson320b91e2DecodeGithubComClambinSciensanoApiclient(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *APIVaccinationsResponseEntry) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson320b91e2DecodeGithubComClambinSciensanoApiclient(l, v)
}
func easyjson320b91e2DecodeGithubComClambinSciensanoApiclient1(in *jlexer.Lexer, out *APIVaccinationsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(APIVaccinationsResponse, 0, 0)
			} else {
				*out = APIVaccinationsResponse{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 APIVaccinationsResponseEntry
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson320b91e2EncodeGithubComClambinSciensanoApiclient1(out *jwriter.Writer, in APIVaccinationsResponse) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v APIVaccinationsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson320b91e2EncodeGithubComClambinSciensanoApiclient1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v APIVaccinationsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson320b91e2EncodeGithubComClambinSciensanoApiclient1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *APIVaccinationsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson320b91e2DecodeGithubComClambinSciensanoApiclient1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *APIVaccinationsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson320b91e2DecodeGithubComClambinSciensanoApiclient1(l, v)
}
