// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	bracket "github.com/clambin/sciensano/v2/internal/population/bracket"

	mock "github.com/stretchr/testify/mock"
)

// PopulationFetcher is an autogenerated mock type for the PopulationFetcher type
type PopulationFetcher struct {
	mock.Mock
}

type PopulationFetcher_Expecter struct {
	mock *mock.Mock
}

func (_m *PopulationFetcher) EXPECT() *PopulationFetcher_Expecter {
	return &PopulationFetcher_Expecter{mock: &_m.Mock}
}

// GetForAgeBracket provides a mock function with given fields: _a0
func (_m *PopulationFetcher) GetForAgeBracket(_a0 bracket.Bracket) int {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(bracket.Bracket) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// PopulationFetcher_GetForAgeBracket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForAgeBracket'
type PopulationFetcher_GetForAgeBracket_Call struct {
	*mock.Call
}

// GetForAgeBracket is a helper method to define mock.On call
//   - _a0 bracket.Bracket
func (_e *PopulationFetcher_Expecter) GetForAgeBracket(_a0 interface{}) *PopulationFetcher_GetForAgeBracket_Call {
	return &PopulationFetcher_GetForAgeBracket_Call{Call: _e.mock.On("GetForAgeBracket", _a0)}
}

func (_c *PopulationFetcher_GetForAgeBracket_Call) Run(run func(_a0 bracket.Bracket)) *PopulationFetcher_GetForAgeBracket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bracket.Bracket))
	})
	return _c
}

func (_c *PopulationFetcher_GetForAgeBracket_Call) Return(count int) *PopulationFetcher_GetForAgeBracket_Call {
	_c.Call.Return(count)
	return _c
}

func (_c *PopulationFetcher_GetForAgeBracket_Call) RunAndReturn(run func(bracket.Bracket) int) *PopulationFetcher_GetForAgeBracket_Call {
	_c.Call.Return(run)
	return _c
}

// GetForRegion provides a mock function with given fields: region
func (_m *PopulationFetcher) GetForRegion(region string) int {
	ret := _m.Called(region)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(region)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// PopulationFetcher_GetForRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetForRegion'
type PopulationFetcher_GetForRegion_Call struct {
	*mock.Call
}

// GetForRegion is a helper method to define mock.On call
//   - region string
func (_e *PopulationFetcher_Expecter) GetForRegion(region interface{}) *PopulationFetcher_GetForRegion_Call {
	return &PopulationFetcher_GetForRegion_Call{Call: _e.mock.On("GetForRegion", region)}
}

func (_c *PopulationFetcher_GetForRegion_Call) Run(run func(region string)) *PopulationFetcher_GetForRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *PopulationFetcher_GetForRegion_Call) Return(count int) *PopulationFetcher_GetForRegion_Call {
	_c.Call.Return(count)
	return _c
}

func (_c *PopulationFetcher_GetForRegion_Call) RunAndReturn(run func(string) int) *PopulationFetcher_GetForRegion_Call {
	_c.Call.Return(run)
	return _c
}

// WaitTillReady provides a mock function with given fields: ctx
func (_m *PopulationFetcher) WaitTillReady(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PopulationFetcher_WaitTillReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitTillReady'
type PopulationFetcher_WaitTillReady_Call struct {
	*mock.Call
}

// WaitTillReady is a helper method to define mock.On call
//   - ctx context.Context
func (_e *PopulationFetcher_Expecter) WaitTillReady(ctx interface{}) *PopulationFetcher_WaitTillReady_Call {
	return &PopulationFetcher_WaitTillReady_Call{Call: _e.mock.On("WaitTillReady", ctx)}
}

func (_c *PopulationFetcher_WaitTillReady_Call) Run(run func(ctx context.Context)) *PopulationFetcher_WaitTillReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *PopulationFetcher_WaitTillReady_Call) Return(_a0 error) *PopulationFetcher_WaitTillReady_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PopulationFetcher_WaitTillReady_Call) RunAndReturn(run func(context.Context) error) *PopulationFetcher_WaitTillReady_Call {
	_c.Call.Return(run)
	return _c
}

// NewPopulationFetcher creates a new instance of PopulationFetcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPopulationFetcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PopulationFetcher {
	mock := &PopulationFetcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
