name: Build

on:
  push:
    branches:
    - master
    - cache
    paths-ignore:
      - '**.md'
      - 'assets/grafana/dashboards/**'
      - 'assets/screenshots/**'

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: golangci/golangci-lint-action@v3
        with:
          args: --issues-exit-code=0
  go-vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: vet
        run: go vet ./...
        shell: bash
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: test
        run: |
          go test ./... -race -coverprofile=coverage.txt -covermode=atomic
          grep -v "_easyjson.go" coverage.txt > coverage.filtered
        shell: bash
      - name: upload code coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.filtered
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    needs:
      - go-test
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      target: sciensano
