name: Build

on:
  push:
    branches:
    - master
    - workflows
    paths-ignore:
      - '**.md'
      - 'assets/grafana/dashboards/**'
      - 'assets/screenshots/**'

jobs:
  test:
    uses: clambin/workflows/.github/workflows/build.yaml@main
    with:
      target: sciensano
