name: Test

on:
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '**.md'
      - 'assets/grafana/dashboards/**'
  pull_request_target:

jobs:
  test:
    uses: clambin/workflows/.github/workflows/test.yaml@main